name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: |
          # Build your site here
          echo "Site built successfully"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ github.run_id }} # Append a unique run ID to avoid naming conflicts
          path: ./public # Replace with the actual path to your build output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages-${{ github.run_id }} # Match the updated artifact name

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
